name: Generate and Deploy GH Pages
on:
  workflow_dispatch:
  push:
    branches:
    - stage

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stage

      - name: Set Node.js 12.x
        uses: actions/setup-node@v1.1.0
        with:
          node-version: 12.x

      - name: npm install
        run: npm install

      - name: npm generate
        run: npm run generate

      - name: List output files
        run: ls

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.3.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./dist
