name: Generate and Deploy GH Pages
on:
  workflow_dispatch:
  push:
    branches:
    - stage

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: stage
      - name: Set Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: npm install
        run: npm install

      - name: npm generate
        run: npm run generate

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
